Cli
crossopt/SoftwareDesign-HW pull request #1
Opened 2020-01-25 11:21 UTC by crossopt

2020-01-25 17:58 UTC, yurii-litvinov requested changes
Нелишне инструкцию по запуску CLI из консоли. Если как запустить юнит-тесты ещё можно понять из конфига CI, то как запустить саму программу, можно только догадаться или понять, прочитав код.

2020-01-25 17:58 UTC, yurii-litvinov commented on cli/src/commands.py
> +        sys.exit(0)
Я б не пользовался sys.exit, потому как если мы хотим что-то сделать после выполнения любой команды (например, логирование или сохранение на диск истории команд), это будет сложно. И вообще, когда команда управляет тем, как работает шелл в целом, это как-то противоестественно. Лучше придумать какой-то механизм сигнализации основному циклу, что надо выйти.

2020-01-25 17:58 UTC, yurii-litvinov commented on cli/src/interpreter.py
> +        self._variables = {}
Более "архитектурно" было бы вынести _SUPPORTED_COMMANDS и _variables в отдельные классы. Иначе такие важные вещи, как создание команды и хранение переменных окружения, упоминаются в коде между делом (а в случае с _variables так и вообще не очень видны при беглом просмотре).

2020-01-25 17:58 UTC, yurii-litvinov commented on cli/src/interpreter.py
> +        self._variables = {}
Более "архитектурно" было бы вынести _SUPPORTED_COMMANDS и _variables в отдельные классы. Иначе такие важные вещи, как создание команды и хранение переменных окружения, упоминаются в коде между делом (а в случае с _variables так и вообще не очень видны при беглом просмотре).

2020-01-25 17:58 UTC, yurii-litvinov commented on cli/src/interpreter.py
> +        if len(command) == 1 and re.match(re.compile(r'\w+?=\w*'), command[0]):
Тут тем более `len(command) == 1 and re.match(re.compile(r'\w+?=\w*')` следовало бы вынести в отдельную функцию с адекватным именем. Иначе неочевидно, что делает этот код.

2020-01-25 17:58 UTC, yurii-litvinov commented on cli/src/interface.py
> +            result += os.linesep + input('> ')
👍

2020-01-25 20:00 UTC, crossopt commented on cli/src/commands.py
> +        sys.exit(0)
Исправила, удалила класс Exit(Command) и заменила на break'и.

В своё оправдание могу сказать, что известные дальнейшие предполагаемые разрешения не предполагали логирование и т.д.

А в таких предположениях если кинуть sys.exit, код будет проще.

2020-01-25 20:02 UTC, crossopt commented on cli/src/interpreter.py
> +        self._variables = {}
С _variables абсолютно согласна, а про _SUPPORTED_COMMANDS я может недопоняла, как это должно было выглядеть.

Как-то класс на константный dict меня слишком угнетает. Единственное, что может полезно для поддержки интерпретаторов с различным набором команд?

2020-01-25 20:03 UTC, crossopt commented
> Нелишне инструкцию по запуску CLI из консоли. Если как запустить юнит-тесты ещё можно понять из конфига CI, то как запустить саму программу, можно только догадаться или понять, прочитав код.

Написала пару слов в README

2020-01-26 18:35 UTC, yurii-litvinov commented on README.md
> +1. A command line bash-like interpreter. Should be run using `cli/src/interface.py`.
Мм, я б написал что-нить в духе `Под Windows выполните команду set PYTHONPATH=cli, затем python cli/src/interface.py`, аналогично для линукса. Гипотетически не все, кто хотят запускать шелл, знают Питон, а так сходу штуку с pythonpath нагуглить сложно.

2020-01-26 18:35 UTC, yurii-litvinov commented on cli/src/interpreter.py
> +        self._variables = {}
Ага, на Питоне это не принято и смотрится жутковато, но я предупреждал, что курс по архитектуре, овердизайн и всё такое. В конце концов, питон --- язык для небольших скриптов, а не для систем, где вообще нужна какая-нибудь архитектура.

2020-01-26 18:35 UTC, yurii-litvinov approved these changes

2020-01-26 19:02 UTC, merged